services:
  webdav:
    container_name: webdav
    image: ${WEBDAV_IMAGE}
    restart: always
    ports:
      - ${WEBDAV_PORT}:80
    environment:
      - AUTH_TYPE=Digest
      - USERNAME=${USER_NAME}
      - PASSWORD=${USER_PASS}
    volumes:
      - ./datas:/var/lib/dav/data