services:
  memos:
    container_name: memos
    image: ${MEMOS_IMAGE}
    environment:
      - MEMOS_PORT=${MEMOS_PORT}
    ports:
      - ${MEMOS_PORT}:${MEMOS_PORT}
    volumes:
      - ./memos:/var/opt/memos
